name: Build with Docker Build Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub (Docker Build Cloud)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_ACCOUNT }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx (Docker Cloud)
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "docker://shettyanna/gen-ai-testing"

      - name: Build and push (Docker Cloud)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_ACCOUNT }}/genai-demo:latest
          outputs: type=registry
